/**
 * Admin session primitives (WebCrypto HMAC).
 *
 * Design:
 * - Passwords are stored as SHA-256 hex digests in `admins.password`.
 *   NOTE: SHA-256 is unsalted and fast; it is adequate only because admin
 *   passwords are high-entropy secrets generated by the seeding script.
 *   Migrate to PBKDF2/Argon2 before onboarding human-chosen passwords.
 * - Session cookies carry an HMAC-SHA-256 signed payload. The signing key
 *   comes from the `ADMIN_SESSION_SECRET` binding; tokens cannot be forged
 *   without it.
 */

const encoder = new TextEncoder();

export const SESSION_COOKIE = 'admin_session';
export const SESSION_TTL_SECONDS = 8 * 60 * 60; // 8 hours

function getSecret(env) {
  const secret = env.ADMIN_SESSION_SECRET;
  if (!secret) {
    throw new Error('ADMIN_SESSION_SECRET binding is not configured');
  }
  return secret;
}

/** Throws if the session signing secret is absent. Call before minting tokens. */
export function assertSecretConfigured(env) {
  getSecret(env);
}

function toHex(buffer) {
  return Array.from(new Uint8Array(buffer))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

function toBase64Url(text) {
  return btoa(text).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function fromBase64Url(value) {
  const padded = value.replace(/-/g, '+').replace(/_/g, '/');
  return atob(padded + '='.repeat((4 - (padded.length % 4)) % 4));
}

/** SHA-256 hex digest of a UTF-8 string. */
export async function sha256Hex(text) {
  const digest = await crypto.subtle.digest('SHA-256', encoder.encode(text));
  return toHex(digest);
}

async function hmacKey(env) {
  return crypto.subtle.importKey(
    'raw',
    encoder.encode(getSecret(env)),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
}

/** Constant-time comparison of two hex strings. */
export function timingSafeEqualString(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

/** Serializes a session payload and appends its HMAC signature. */
export async function signSession(env, payload) {
  const signature = toHex(
    await crypto.subtle.sign('HMAC', await hmacKey(env), encoder.encode(payload)),
  );
  return `${toBase64Url(payload)}.${signature}`;
}

/** Verifies a token and returns its payload, or null if invalid/expired. */
export async function verifySession(env, token) {
  if (!token || !token.includes('.')) return null;
  const [encoded, signature] = token.split('.');
  if (!encoded || !signature) return null;

  let payloadJson;
  try {
    payloadJson = fromBase64Url(encoded);
  } catch {
    return null;
  }

  const expected = toHex(
    await crypto.subtle.sign('HMAC', await hmacKey(env), encoder.encode(payloadJson)),
  );
  if (!timingSafeEqualString(signature, expected)) return null;

  let payload;
  try {
    payload = JSON.parse(payloadJson);
  } catch {
    return null;
  }

  if (typeof payload.exp !== 'number' || payload.exp * 1000 <= Date.now()) {
    return null;
  }
  return payload;
}

export function buildSessionCookie(token) {
  return [
    `${SESSION_COOKIE}=${token}`,
    'Path=/',
    'HttpOnly',
    'Secure',
    'SameSite=Strict',
    `Max-Age=${SESSION_TTL_SECONDS}`,
  ].join('; ');
}

export function buildClearedCookie() {
  return `${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;
}

/** Extracts the session cookie value from a request. */
export function readSessionCookie(request) {
  const header = request.headers.get('Cookie') || '';
  const match = header.match(new RegExp(`(?:^|;\\s*)${SESSION_COOKIE}=([^;]+)`));
  return match ? match[1] : null;
}
